dtitle: Michelle Cao # your name (or website title) here
logo: "/images/Michelle-28_Original.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/mcao16/">LinkedIn</a> |
  <a href="https://github.com/michcao">GitHub</a>
  </p>
  
  <p align="left">
  <b>Colgate University</b>, <i>BA</i>
  <br>
  <b>Columbia University</b> School of International and Public Affairs, <i>MPA</i>
  <br><br>
  Second description
  <br><br>
   </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
